name: My f workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repor
              uses: actions/checkout@v4
            - name: welcome message
              run: |
                echo "my first workflow"
                ls
                cat README.md


