name: Matrix COnfiguration

on:
  push:
  workflow_dispatch: 

jobs:
    deploy:
      strategy:
        matrix:
          os: [ubuntu-lates,ubuntu-20.04,windows-latest]
          images: [hello-world,alpine]
      runs-on: ${{matrix.os}}
      steps:
      - name: Echo docker details
        run: docker info
      - name: Run IMages
        run: docker run ${{matrix.images}}