name: Multi Job demo

on: push

jobs:
 build_job:
    runs-on: ubuntu-latest
    steps:
    - name: List all file
      run: ls -ltra
    - name: Install Cowway
      run: sudo apt-get install cowsay -y
    - name: Install Cowsay COmmand
      run: cowsay -f dragon  "Run for a cover i am Dragon" >> drg.txt
    - name: Upload dragon file
      uses: actions/upload-artifact@v4
      with:
        name: dragon text file
        path: drg.txt
    

 test_job_2:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    
    - name: Upload dragon file
      uses: actions/download-artifact@v4
      with:
        name: dragon text file
          
    - name: Test file exists
      run: grep -i "dragon" drg.txt


 deploy_job_3:
    needs: test_job_2
    runs-on: ubuntu-latest
    steps:
    
    - name: Upload dragon file
      uses: actions/download-artifact@v4
      with:
        name: dragon text file
    
    - name: contant of dragon file
      run: cat drg.txt
    - name: List all file
      run: ls -ltra
       
    
