name: Generate Aschi Work flow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repor
              uses: actions/checkout@v4

            - name: List Repo
              run: ls -ltra

            - name: Executing script
              run: |
               chmod +x as.sh
               ./as.sh