name: Exploring variable and secrets

on:
    push

env:
    CONTAINER_REGISTER: docker.io
    IMAGE_NAME: github-actions-nginx


jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: docker build -t ${{env.CONTAINER_REGISTER}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
        - name: Docker login
          run: docker login --username=${{env.DOCKER_USERNAME}} --password=${{env.DOCKER_PASSWORD}}
        - name: Docker publish
          run: docker push ${{env.CONTAINER_REGISTER}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
    
    deploy:
        needs: docker
        runs-on: ubuntu-latest
        steps:
        - name: Docker Run
          run: docker run -d 8080:80 ${{env.CONTAINER_REGISTER}}/${{env.DOCKER_USERNAME}}/${{env.IMAGE_NAME}}:latest
